import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, HeartHandshake, Leaf, LockKeyhole, UserRoundCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AreaCards, Eyebrow, FaqList, LocationBlock, Steps } from "@/components/page-parts";
import { whatsappUrl } from "@/lib/site-data";
import drFrederickAsset from "@/assets/dr-frederick-parreira.png.asset.json";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Dr. Frederick Parreira | Saúde Integrativa" }, { name: "description", content: "Psicologia, saúde mental, biomedicina integrativa e estética com atendimento individualizado em Juiz de Fora." }, { property: "og:title", content: "Espaço de Saúde Integrativa | Dr. Frederick Parreira" }, { property: "og:description", content: "Cuidado completo para a mente, o corpo e o bem-estar." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/" }], scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "ProfessionalService", name: "Espaço de Saúde Integrativa Dr. Frederick Parreira", telephone: "+55 32 99193-1779", address: { "@type": "PostalAddress", streetAddress: "Rua Fernando Lobo, 102, Sala 704", addressLocality: "Juiz de Fora", addressRegion: "MG", addressCountry: "BR" } }) }] }),
  component: HomePage,
});

function HomePage() {
  return <>
    <section className="relative overflow-hidden border-b border-border bg-secondary/35"><div className="container-site grid min-h-[calc(100svh-5rem)] items-center gap-10 py-12 lg:grid-cols-[1.05fr_.95fr] lg:py-16"><div className="relative z-10"><Eyebrow>Espaço de Saúde Integrativa</Eyebrow><h1 className="mt-6 max-w-3xl text-balance font-display text-5xl leading-[1.02] md:text-7xl">Cuidado completo para a mente, o corpo e o bem-estar.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground md:text-lg">Psicologia, saúde mental, biomedicina integrativa e estética em um espaço pensado para um atendimento individualizado, humano e acolhedor.</p><div className="mt-7 border-l-2 border-gold pl-5"><p className="font-display text-2xl">Dr. Frederick Parreira</p><p className="mt-1 text-sm text-muted-foreground">Psicólogo • CRP 04/86194 &nbsp; | &nbsp; Biomédico • CRBM 30421</p></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><a href={whatsappUrl} target="_blank" rel="noreferrer">Agende sua consulta <ArrowRight /></a></Button><Button asChild size="lg" variant="outline"><Link to="/servicos">Conheça nossos serviços</Link></Button></div></div><div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-6 border border-gold/20" /><img src={drFrederickAsset.url} alt="Dr. Frederick Parreira — Psicólogo e Biomédico" className="relative aspect-[4/5] w-full object-cover" loading="eager" /></div></div></section>
    <section className="section-space"><div className="container-site"><div className="max-w-2xl"><Eyebrow>Atuação profissional</Eyebrow><h2 className="mt-4 font-display text-4xl md:text-5xl">Cuidado integrado em diferentes áreas da saúde</h2><p className="mt-4 leading-7 text-muted-foreground">Conheça as áreas de atendimento do Espaço de Saúde Integrativa Dr. Frederick Parreira.</p></div><div className="mt-10"><AreaCards /></div></div></section>
    <section className="section-space bg-muted/55"><div className="container-site grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="aspect-[4/5] overflow-hidden bg-secondary"><img src="/fred-perfil.png" alt="Retrato profissional do Dr. Frederick Parreira" loading="lazy" className="h-full w-full object-cover" /></div><div><Eyebrow>Sobre</Eyebrow><h2 className="mt-4 font-display text-4xl md:text-5xl">Cuidado profissional com um olhar para cada pessoa</h2><div className="mt-6 space-y-4 leading-7 text-muted-foreground"><p>Dr. Frederick Parreira atua nas áreas de Psicologia e Biomedicina, desenvolvendo um trabalho direcionado à saúde mental, saúde integrativa, estética e bem-estar.</p><p>Sua proposta de atendimento parte de uma visão ampla do indivíduo, respeitando as particularidades e os limites de cada área profissional.</p><p>No Espaço de Saúde Integrativa, cada atendimento é conduzido de forma individualizada, buscando unir conhecimento técnico, escuta, acolhimento e acompanhamento profissional.</p></div><div className="mt-7 grid max-w-lg grid-cols-2 gap-3"><div className="border-l-2 border-psychology pl-4"><strong>Psicólogo</strong><span className="block text-sm text-muted-foreground">CRP 04/86194</span></div><div className="border-l-2 border-biomedicine pl-4"><strong>Biomédico</strong><span className="block text-sm text-muted-foreground">CRBM 30421</span></div></div><Button asChild variant="outline" className="mt-8"><Link to="/sobre">Conheça minha trajetória <ArrowRight /></Link></Button></div></div></section>
    <section className="section-space"><div className="container-site"><Eyebrow>Como funciona</Eyebrow><h2 className="mt-4 mb-10 font-display text-4xl">Atendimento em quatro etapas</h2><Steps /></div></section>
    <section className="section-space bg-secondary/35"><div className="container-site"><div className="text-center"><Eyebrow>Diferenciais</Eyebrow><h2 className="mt-4 font-display text-4xl md:text-5xl">Um espaço pensado para cuidar de você</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[[HeartHandshake,"Atendimento Humanizado","Escuta, acolhimento e respeito às particularidades de cada pessoa."],[UserRoundCheck,"Atendimento Individualizado","Cada acompanhamento é planejado considerando as necessidades identificadas na avaliação."],[Leaf,"Saúde Integrativa","Diferentes possibilidades de cuidado, respeitando as competências de cada área profissional."],[LockKeyhole,"Ambiente Acolhedor","Estrutura preparada para proporcionar conforto, privacidade e tranquilidade."]].map(([Icon,title,text]) => { const C = Icon as typeof HeartHandshake; return <article key={String(title)} className="border border-border bg-background p-6"><C className="size-6 text-gold"/><h3 className="mt-6 font-display text-2xl">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{String(text)}</p></article>})}</div></div></section>
    <section className="section-space"><div className="container-site"><LocationBlock /></div></section>
    <section className="section-space border-y border-border bg-muted/45"><div className="container-site text-center"><Eyebrow>Depoimentos</Eyebrow><h2 className="mt-4 font-display text-4xl">Experiências de quem já passou por aqui</h2><div className="mx-auto mt-8 max-w-2xl border border-dashed border-border bg-background p-8 text-muted-foreground"><p>Este espaço está preparado para receber depoimentos reais, mediante autorização, quando estiverem disponíveis.</p></div></div></section>
    <section className="section-space"><div className="container-site"><div className="text-center"><Eyebrow>Perguntas frequentes</Eyebrow><h2 className="mt-4 mb-8 font-display text-4xl">Informações para seu primeiro contato</h2></div><FaqList /><div className="mt-8 text-center"><Button asChild variant="outline"><Link to="/faq">Ver todas as informações</Link></Button></div></div></section>
  </>;
}