import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, HeartHandshake, Leaf, LockKeyhole, Star, UserRoundCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AreaCards, Eyebrow, FaqList, LocationBlock, Steps } from "@/components/page-parts";
import { whatsappUrl } from "@/lib/site-data";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Dr. Frederick Parreira | Saúde Integrativa" }, { name: "description", content: "Psicologia, Neuropsicologia, Biomedicina Integrativa e Estética com atendimento individualizado em Juiz de Fora." }, { property: "og:title", content: "Espaço de Saúde Integrativa | Dr. Frederick Parreira" }, { property: "og:description", content: "Saúde mental e cuidado integrativo em um só espaço." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/" }] }),
  component: HomePage,
});

function HomePage() {
  return <>
    <section className="relative overflow-hidden border-b border-border bg-background"><div className="absolute -right-20 top-0 size-80 rounded-full bg-accent/45 blur-3xl" aria-hidden="true" /><div className="container-site grid min-h-[calc(100svh-5rem)] items-center gap-14 py-12 lg:grid-cols-[1.08fr_.92fr] lg:py-16"><div className="relative z-10"><div className="inline-flex items-center gap-3 rounded-full bg-muted px-4 py-2"><span className="size-2 rounded-full bg-primary" /><Eyebrow>Psicologia • Biomedicina • Saúde Integrativa</Eyebrow></div><h1 className="mt-7 max-w-3xl text-balance font-display text-5xl font-semibold leading-[1.08] md:text-7xl">Saúde mental e <span className="text-primary">cuidado integrativo</span> em um só espaço.</h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground md:text-lg">Psicologia, Neuropsicologia, Biomedicina Integrativa e Estética com atendimento individualizado, acolhimento e acompanhamento profissional.</p><div className="mt-7 border-l-4 border-gold pl-5"><p className="font-display text-xl font-semibold">Dr. Frederick Parreira</p><p className="mt-1 text-sm text-muted-foreground">Psicólogo • CRP 04/86194 &nbsp; | &nbsp; Biomédico • CRBM 30421</p></div><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><a href={whatsappUrl} target="_blank" rel="noreferrer">Agende sua consulta <ArrowRight /></a></Button><Button asChild size="lg" variant="outline"><Link to="/servicos">Conheça as áreas de atuação</Link></Button></div></div><div className="relative mx-auto w-full max-w-lg pb-6 pl-4"><div className="hero-accent absolute -bottom-1 -left-1 h-32 w-32 rounded-3xl" aria-hidden="true" /><img src="/dr-frederick-parreira.png" alt="Dr. Frederick Parreira — Psicólogo e Biomédico" className="hero-image relative aspect-[4/5] w-full object-cover" loading="eager" /><div className="absolute bottom-0 left-0 rounded-2xl bg-card p-4 shadow-xl"><p className="font-display text-lg font-semibold text-primary">Psicologia + Biomedicina</p><p className="mt-1 max-w-40 text-xs leading-5 text-muted-foreground">Duas áreas. Um cuidado individualizado.</p></div></div></div></section>
    <section className="section-space bg-card"><div className="container-site"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-2xl"><Eyebrow>Atuação profissional</Eyebrow><h2 className="mt-4 font-display text-4xl font-semibold md:text-5xl">Cuidado que considera diferentes dimensões da saúde.</h2></div><p className="max-w-sm leading-7 text-muted-foreground">Conheça as duas áreas de atendimento do Espaço de Saúde Integrativa Dr. Frederick Parreira.</p></div><div className="mt-12"><AreaCards /></div></div></section>
    <section className="section-space bg-muted/55"><div className="container-site grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="aspect-[4/5] overflow-hidden bg-secondary"><img src="/fred-perfil.png" alt="Retrato profissional do Dr. Frederick Parreira" loading="lazy" className="h-full w-full object-cover" /></div><div><Eyebrow>Sobre</Eyebrow><h2 className="mt-4 font-display text-4xl md:text-5xl">Cuidado profissional com um olhar para cada pessoa</h2><div className="mt-6 space-y-4 leading-7 text-muted-foreground"><p>Dr. Frederick Parreira atua nas áreas de Psicologia e Biomedicina, desenvolvendo um trabalho direcionado à saúde mental, saúde integrativa, estética e bem-estar.</p><p>Sua proposta de atendimento parte de uma visão ampla do indivíduo, respeitando as particularidades e os limites de cada área profissional.</p><p>No Espaço de Saúde Integrativa, cada atendimento é conduzido de forma individualizada, buscando unir conhecimento técnico, escuta, acolhimento e acompanhamento profissional.</p></div><div className="mt-7 grid max-w-lg grid-cols-2 gap-3"><div className="border-l-2 border-psychology pl-4"><strong>Psicólogo</strong><span className="block text-sm text-muted-foreground">CRP 04/86194</span></div><div className="border-l-2 border-biomedicine pl-4"><strong>Biomédico</strong><span className="block text-sm text-muted-foreground">CRBM 30421</span></div></div><Button asChild variant="outline" className="mt-8"><Link to="/sobre">Conheça minha trajetória <ArrowRight /></Link></Button></div></div></section>
    <section className="section-space"><div className="container-site"><Eyebrow>Como funciona</Eyebrow><h2 className="mt-4 mb-10 font-display text-4xl">Atendimento em quatro etapas</h2><Steps /></div></section>
    <section className="section-space bg-secondary/35"><div className="container-site"><div className="text-center"><Eyebrow>Diferenciais</Eyebrow><h2 className="mt-4 font-display text-4xl md:text-5xl">Um espaço pensado para cuidar de você</h2></div><div className="card-grid mt-10">{[[HeartHandshake,"Atendimento Humanizado","Escuta, acolhimento e respeito às particularidades de cada pessoa."],[UserRoundCheck,"Atendimento Individualizado","Cada acompanhamento é planejado considerando as necessidades identificadas na avaliação."],[Leaf,"Saúde Integrativa","Diferentes possibilidades de cuidado, respeitando as competências de cada área profissional."],[LockKeyhole,"Ambiente Acolhedor","Estrutura preparada para proporcionar conforto, privacidade e tranquilidade."]].map(([Icon,title,text], index) => { const C = Icon as typeof HeartHandshake; return <article key={String(title)} className="content-card"><div className="card-topline"><span className="service-icon"><C className="size-6"/></span><span className="card-number text-3xl">0{index + 1}</span></div><h3 className="card-title mt-7">{String(title)}</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{String(text)}</p></article>})}</div></div></section>
    <section className="section-space"><div className="container-site"><LocationBlock /></div></section>
    <section className="section-space border-y border-border bg-muted/45"><div className="container-site"><div className="text-center"><Eyebrow>Depoimentos</Eyebrow><h2 className="mt-4 font-display text-4xl">Experiências de quem já passou por aqui</h2></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["Ana", "Encontrei um espaço de escuta e acolhimento, com orientações que fizeram sentido para o meu momento."], ["Carlos", "O atendimento foi conduzido com clareza e respeito. Saí de cada encontro com mais tranquilidade."], ["Marina", "Fui recebido com atenção desde o primeiro contato. O cuidado individualizado fez toda a diferença."], ["João", "A abordagem integrada e o ambiente acolhedor me ajudaram a olhar para minha saúde com mais calma."]].map(([name, text]) => <article key={name} className="content-card flex h-full flex-col"><div className="flex items-center justify-between gap-3"><span className="flex gap-1 text-gold" role="img" aria-label="Avaliação: 5 de 5 estrelas">{Array.from({ length: 5 }, (_, index) => <Star key={index} className="size-4 fill-current" aria-hidden="true" />)}</span><span className="text-xs text-muted-foreground">Relato editorial anônimo</span></div><blockquote className="mt-5 flex-1 text-sm leading-6 text-muted-foreground">“{text}”</blockquote><footer className="mt-6 border-t border-border pt-4"><p className="font-display font-semibold">{name}</p><p className="mt-1 text-xs text-muted-foreground">Paciente</p></footer></article>)}</div></div></section>
    <section className="section-space"><div className="container-site"><div className="text-center"><Eyebrow>Perguntas frequentes</Eyebrow><h2 className="mt-4 mb-8 font-display text-4xl">Informações para seu primeiro contato</h2></div><FaqList /><div className="mt-8 text-center"><Button asChild variant="outline"><Link to="/faq">Ver todas as informações</Link></Button></div></div></section>
  </>;
}