import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { EmptyState, StatusBadge } from '@/components/admin/admin-ui';
import { displayDate, professionalAreas, type ProfessionalDocument, type ProfessionalArea } from '@/lib/admin/documents';

export function DocumentHistory({ documents, loading, onView, onPrint, onDuplicate, onDelete }: { documents: ProfessionalDocument[]; loading: boolean; onView: (document: ProfessionalDocument) => void; onPrint: (document: ProfessionalDocument) => void; onDuplicate: (document: ProfessionalDocument) => void; onDelete: (document: ProfessionalDocument) => void }) {
  const [area, setArea] = useState<ProfessionalArea | 'all'>('all');
  const [query, setQuery] = useState('');
  const rows = documents.filter(document => (area === 'all' || document.area === area) && document.patient_name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
  return <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-display text-xl">Documentos recentes</h3><div className="my-5 flex flex-wrap gap-2">{(['all', 'psicologia', 'biomedicina'] as const).map(key => <Button key={key} variant={area === key ? 'default' : 'outline'} aria-pressed={area === key} onClick={() => setArea(key)}>{key === 'all' ? 'Todos' : professionalAreas[key].label}</Button>)}<Input aria-label="Buscar paciente" placeholder="Buscar paciente" className="sm:ml-auto sm:max-w-xs" value={query} onChange={event => setQuery(event.target.value)} /></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs text-slate-500"><tr>{['Paciente', 'Data', 'Área profissional', 'Registro', 'Tipo de documento', 'Status', 'Ações'].map(label => <th key={label} className="whitespace-nowrap px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{rows.map(document => <tr key={document.id} className="border-b last:border-0"><td className="px-3 py-4 font-medium">{document.patient_name}</td><td className="whitespace-nowrap px-3 py-4">{displayDate(document.attendance_date)}</td><td className="px-3 py-4">{professionalAreas[document.area].label}</td><td className="whitespace-nowrap px-3 py-4">{professionalAreas[document.area].registration}</td><td className="px-3 py-4">{document.document_type}</td><td className="px-3 py-4"><StatusBadge status={document.status} /></td><td className="px-3 py-4"><div className="flex flex-wrap gap-1"><Button size="sm" variant="ghost" onClick={() => onView(document)}>Visualizar</Button><Button size="sm" variant="ghost" onClick={() => onPrint(document)}>Imprimir</Button><Button size="sm" variant="ghost" onClick={() => onDuplicate(document)}>Duplicar</Button><Button size="sm" variant="ghost" className="text-red-600" onClick={() => onDelete(document)}>Excluir</Button></div></td></tr>)}</tbody></table></div>{loading ? <p role="status" className="py-8 text-center text-sm text-slate-500">Carregando documentos...</p> : rows.length === 0 && <EmptyState title={documents.length === 0 ? 'Nenhum documento salvo.' : 'Nenhum documento encontrado.'} description="Os documentos salvos ficam disponíveis somente para sua conta administrativa." />}</section>;
}
