import { useId, useState } from 'react';
import { Copy, Pencil, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { SectionCard } from '@/components/admin/admin-ui';
import { emptyItem, type DocumentContent, type PrescriptionItem as Item, type ExamItem } from '@/lib/admin/documents';

export function Field({ label, value, onChange, multiline, type = 'text', required = false, maxLength }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean; type?: string; required?: boolean; maxLength?: number }) {
  const id = useId();
  return <div className="grid gap-2"><Label htmlFor={id}>{label}{required && ' *'}</Label>{multiline ? <Textarea id={id} className="min-h-32 bg-white" value={value} onChange={event => onChange(event.target.value)} required={required} maxLength={maxLength} /> : <Input id={id} type={type} className="bg-white" value={value} onChange={event => onChange(event.target.value)} required={required} />}</div>;
}
export function PatientForm({ patient, onChange }: { patient: DocumentContent['patient']; onChange: (value: DocumentContent['patient']) => void }) {
  return <SectionCard title="Dados do paciente"><div className="grid gap-4 sm:grid-cols-2">{([['name', 'Nome completo', 'text', true], ['cpf', 'CPF', 'text', false], ['birthDate', 'Data de nascimento', 'date', false], ['phone', 'Telefone', 'tel', false], ['date', 'Data do atendimento', 'date', true]] as const).map(([key, label, type, required]) => <Field key={key} label={label} type={type} required={required} value={patient[key]} onChange={value => onChange({ ...patient, [key]: value })} />)}</div><p className="mt-4 text-xs text-slate-500">* Campos obrigatórios. Dados utilizados apenas neste documento.</p></SectionCard>;
}
export function PrescriptionItem({ item, index, onChange, onDuplicate, onDelete }: { item: Item; index: number; onChange: (item: Item) => void; onDuplicate: () => void; onDelete: () => void }) {
  const [editing, setEditing] = useState(true);
  return <div className="rounded-xl border border-slate-200 p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><strong>{index + 1}. {item.product || 'Novo item'}</strong><div className="flex flex-wrap gap-1"><Button type="button" size="sm" variant="ghost" onClick={() => setEditing(!editing)}><Pencil className="size-3" />{editing ? 'Recolher' : 'Editar'}</Button><Button type="button" size="sm" variant="ghost" onClick={onDuplicate}><Copy className="size-3" />Duplicar</Button><Button type="button" size="sm" variant="ghost" onClick={onDelete}><Trash2 className="size-3" />Excluir</Button></div></div>{editing && <div className="grid gap-4 sm:grid-cols-2">{([['product', 'Medicamento/produto'], ['presentation', 'Apresentação'], ['concentration', 'Concentração'], ['quantity', 'Quantidade'], ['route', 'Via de administração'], ['dosage', 'Posologia / modo de usar'], ['duration', 'Duração do tratamento'], ['notes', 'Observações']] as const).map(([key, label]) => <Field key={key} label={label} value={item[key]} multiline={key === 'dosage' || key === 'notes'} onChange={value => onChange({ ...item, [key]: value })} />)}</div>}</div>;
}
export function PrescriptionEditor({ content, onChange }: { content: DocumentContent; onChange: (value: DocumentContent) => void }) {
  const update = (items: Item[]) => onChange({ ...content, items });
  return <SectionCard title="PRESCRIÇÃO"><div className="mb-5 flex flex-wrap gap-2"><Button type="button" variant={content.mode === 'structured' ? 'default' : 'outline'} aria-pressed={content.mode === 'structured'} onClick={() => onChange({ ...content, mode: 'structured' })}>Prescrição estruturada</Button><Button type="button" variant={content.mode === 'free' ? 'default' : 'outline'} aria-pressed={content.mode === 'free'} onClick={() => onChange({ ...content, mode: 'free' })}>Texto livre</Button></div>{content.mode === 'free' ? <Field label="Prescrição em texto livre" multiline value={content.text} onChange={text => onChange({ ...content, text })} /> : <div className="space-y-4">{content.items.map((item, index) => <PrescriptionItem key={item.id} item={item} index={index} onChange={value => update(content.items.map(row => row.id === item.id ? value : row))} onDuplicate={() => update([...content.items.slice(0, index + 1), { ...item, id: crypto.randomUUID() }, ...content.items.slice(index + 1)])} onDelete={() => update(content.items.filter(row => row.id !== item.id))} />)}<Button type="button" variant="outline" onClick={() => update([...content.items, emptyItem()])}>+ Adicionar item</Button></div>}</SectionCard>;
}
export function ExamRequestEditor({ exams, notes, onChange, onNotes }: { exams: ExamItem[]; notes: string; onChange: (items: ExamItem[]) => void; onNotes: (value: string) => void }) {
  return <SectionCard title="Exames solicitados"><div className="space-y-4">{exams.map((exam, index) => <div key={exam.id} className="space-y-3 rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><strong>Exame {index + 1}</strong><Button type="button" variant="ghost" size="sm" onClick={() => onChange(exams.filter(row => row.id !== exam.id))}>Excluir</Button></div><Field label="Nome do exame" value={exam.name} onChange={name => onChange(exams.map(row => row.id === exam.id ? { ...row, name } : row))} /><Field label="Observação/justificativa opcional" multiline value={exam.notes} onChange={value => onChange(exams.map(row => row.id === exam.id ? { ...row, notes: value } : row))} /></div>)}<Button type="button" variant="outline" onClick={() => onChange([...exams, { id: crypto.randomUUID(), name: '', notes: '' }])}>+ Adicionar exame</Button><Field label="Observações clínicas" multiline value={notes} onChange={onNotes} /></div></SectionCard>;
}
