import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { paymentMethods, type Receipt, type ReceiptSnapshotInput } from '@/lib/admin/receipts';

export function ReceiptEditor({ receipt, error, saving, onClose, onSave }: { receipt: Receipt; error: string; saving: boolean; onClose: () => void; onSave: (input: ReceiptSnapshotInput) => void }) {
  const [form, setForm] = useState<ReceiptSnapshotInput>({ patient_name: receipt.patient_name, patient_cpf: receipt.patient_cpf, service_description: receipt.service_description, amount: receipt.amount, payment_method: receipt.payment_method, payment_date: receipt.payment_date, issue_date: receipt.issue_date, notes: receipt.notes, professional_area: receipt.professional_area, professional_name: receipt.professional_name, professional_title: receipt.professional_title, professional_registration: receipt.professional_registration, city: receipt.city, footer: receipt.footer });
  const set = (key: keyof ReceiptSnapshotInput, value: string | number | null) => setForm(current => ({ ...current, [key]: value }));
  function submit(event: FormEvent) { event.preventDefault(); onSave({ ...form, patient_name: form.patient_name.trim(), service_description: form.service_description.trim(), amount: Number(form.amount) }); }
  return <Dialog open onOpenChange={open => { if (!open && !saving) onClose(); }}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Editar recibo {receipt.receipt_number}</DialogTitle><DialogDescription>Altere os dados deste recibo. O cadastro original do paciente não será alterado. PDFs já enviados não serão atualizados.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><fieldset disabled={saving} className="grid gap-4 sm:grid-cols-2">
    <div className="space-y-2"><Label>Nome do paciente *</Label><Input required value={form.patient_name} onChange={e => set('patient_name', e.target.value)} /></div><div className="space-y-2"><Label>CPF</Label><Input value={form.patient_cpf} onChange={e => set('patient_cpf', e.target.value)} /></div>
    <div className="space-y-2 sm:col-span-2"><Label>Descrição *</Label><Input required maxLength={5000} value={form.service_description} onChange={e => set('service_description', e.target.value)} /></div><div className="space-y-2"><Label>Valor *</Label><Input required type="number" min="0.01" max="999999999.99" step="0.01" value={form.amount} onChange={e => set('amount', Number(e.target.value))} /></div>
    <div className="space-y-2"><Label>Forma de pagamento</Label><select className="h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm" value={form.payment_method} onChange={e => set('payment_method', e.target.value)}>{paymentMethods.map(value => <option key={value}>{value}</option>)}</select></div><div className="space-y-2"><Label>Data pagamento</Label><Input type="date" required={receipt.status === 'FINALIZADO'} value={form.payment_date ?? ''} onChange={e => set('payment_date', e.target.value || null)} /></div><div className="space-y-2"><Label>Data emissão</Label><Input type="date" required value={form.issue_date} onChange={e => set('issue_date', e.target.value)} /></div>
    <div className="space-y-2 sm:col-span-2"><Label>Observações</Label><Textarea maxLength={5000} value={form.notes} onChange={e => set('notes', e.target.value)} /></div><div className="space-y-2"><Label>Área</Label><select className="h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm" value={form.professional_area} onChange={e => set('professional_area', e.target.value)}><option>Psicologia</option><option>Biomedicina</option></select></div><div className="space-y-2"><Label>Nome profissional *</Label><Input required value={form.professional_name} onChange={e => set('professional_name', e.target.value)} /></div>
    {([['professional_title','Título'],['professional_registration','Registro'],['city','Cidade'],['footer','Rodapé']] as const).map(([key,label]) => <div className="space-y-2" key={key}><Label>{label}</Label>{key === 'footer' ? <Textarea value={form[key]} onChange={e => set(key,e.target.value)} /> : <Input value={form[key]} onChange={e => set(key,e.target.value)} />}</div>)}
  </fieldset>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<DialogFooter><Button type="button" variant="outline" disabled={saving} onClick={onClose}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? 'Salvando...' : 'Salvar alterações'}</Button></DialogFooter></form></DialogContent></Dialog>;
}
