/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BiomedicinaRouteImport } from './routes/biomedicina'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EstruturaRouteImport } from './routes/estrutura'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PsicologiaRouteImport } from './routes/psicologia'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgendaRouteImport } from './routes/admin/agenda'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEstatisticasRouteImport } from './routes/admin/estatisticas'
import { Route as AdminFinanceiroRouteImport } from './routes/admin/financeiro'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMedicamentosRouteImport } from './routes/admin/medicamentos'
import { Route as AdminPacientesRouteImport } from './routes/admin/pacientes'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminPacientesIdRouteImport } from './routes/admin/pacientes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BiomedicinaRoute = BiomedicinaRouteImport.update({
  id: '/biomedicina',
  path: '/biomedicina',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EstruturaRoute = EstruturaRouteImport.update({
  id: '/estrutura',
  path: '/estrutura',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PsicologiaRoute = PsicologiaRouteImport.update({
  id: '/psicologia',
  path: '/psicologia',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstatisticasRoute = AdminEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedicamentosRoute = AdminMedicamentosRouteImport.update({
  id: '/medicamentos',
  path: '/medicamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacientesRoute = AdminPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacientesIdRoute = AdminPacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/biomedicina': typeof BiomedicinaRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/estrutura': typeof EstruturaRoute
  '/faq': typeof FaqRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/psicologia': typeof PsicologiaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medicamentos': typeof AdminMedicamentosRoute
  '/admin/pacientes': typeof AdminPacientesRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pacientes/$id': typeof AdminPacientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biomedicina': typeof BiomedicinaRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/estrutura': typeof EstruturaRoute
  '/faq': typeof FaqRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/psicologia': typeof PsicologiaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medicamentos': typeof AdminMedicamentosRoute
  '/admin/pacientes': typeof AdminPacientesRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pacientes/$id': typeof AdminPacientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/biomedicina': typeof BiomedicinaRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/estrutura': typeof EstruturaRoute
  '/faq': typeof FaqRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/psicologia': typeof PsicologiaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medicamentos': typeof AdminMedicamentosRoute
  '/admin/pacientes': typeof AdminPacientesRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pacientes/$id': typeof AdminPacientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/biomedicina'
    | '/blog'
    | '/contato'
    | '/estrutura'
    | '/faq'
    | '/politica-de-privacidade'
    | '/psicologia'
    | '/servicos'
    | '/sobre'
    | '/termos-de-uso'
    | '/admin/agenda'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/estatisticas'
    | '/admin/financeiro'
    | '/admin/login'
    | '/admin/medicamentos'
    | '/admin/pacientes'
    | '/admin/relatorios'
    | '/admin/'
    | '/admin/pacientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biomedicina'
    | '/blog'
    | '/contato'
    | '/estrutura'
    | '/faq'
    | '/politica-de-privacidade'
    | '/psicologia'
    | '/servicos'
    | '/sobre'
    | '/termos-de-uso'
    | '/admin/agenda'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/estatisticas'
    | '/admin/financeiro'
    | '/admin/login'
    | '/admin/medicamentos'
    | '/admin/pacientes'
    | '/admin/relatorios'
    | '/admin'
    | '/admin/pacientes/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/biomedicina'
    | '/blog'
    | '/contato'
    | '/estrutura'
    | '/faq'
    | '/politica-de-privacidade'
    | '/psicologia'
    | '/servicos'
    | '/sobre'
    | '/termos-de-uso'
    | '/admin/agenda'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/estatisticas'
    | '/admin/financeiro'
    | '/admin/login'
    | '/admin/medicamentos'
    | '/admin/pacientes'
    | '/admin/relatorios'
    | '/admin/'
    | '/admin/pacientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BiomedicinaRoute: typeof BiomedicinaRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  EstruturaRoute: typeof EstruturaRoute
  FaqRoute: typeof FaqRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PsicologiaRoute: typeof PsicologiaRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biomedicina': {
      id: '/biomedicina'
      path: '/biomedicina'
      fullPath: '/biomedicina'
      preLoaderRoute: typeof BiomedicinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrutura': {
      id: '/estrutura'
      path: '/estrutura'
      fullPath: '/estrutura'
      preLoaderRoute: typeof EstruturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psicologia': {
      id: '/psicologia'
      path: '/psicologia'
      fullPath: '/psicologia'
      preLoaderRoute: typeof PsicologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estatisticas': {
      id: '/admin/estatisticas'
      path: '/estatisticas'
      fullPath: '/admin/estatisticas'
      preLoaderRoute: typeof AdminEstatisticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medicamentos': {
      id: '/admin/medicamentos'
      path: '/medicamentos'
      fullPath: '/admin/medicamentos'
      preLoaderRoute: typeof AdminMedicamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pacientes': {
      id: '/admin/pacientes'
      path: '/pacientes'
      fullPath: '/admin/pacientes'
      preLoaderRoute: typeof AdminPacientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pacientes/$id': {
      id: '/admin/pacientes/$id'
      path: '/$id'
      fullPath: '/admin/pacientes/$id'
      preLoaderRoute: typeof AdminPacientesIdRouteImport
      parentRoute: typeof AdminPacientesRoute
    }
  }
}

interface AdminPacientesRouteChildren {
  AdminPacientesIdRoute: typeof AdminPacientesIdRoute
}

const AdminPacientesRouteChildren: AdminPacientesRouteChildren = {
  AdminPacientesIdRoute: AdminPacientesIdRoute,
}

const AdminPacientesRouteWithChildren = AdminPacientesRoute._addFileChildren(
  AdminPacientesRouteChildren,
)

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEstatisticasRoute: typeof AdminEstatisticasRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMedicamentosRoute: typeof AdminMedicamentosRoute
  AdminPacientesRoute: typeof AdminPacientesRouteWithChildren
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEstatisticasRoute: AdminEstatisticasRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMedicamentosRoute: AdminMedicamentosRoute,
  AdminPacientesRoute: AdminPacientesRouteWithChildren,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BiomedicinaRoute: BiomedicinaRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  EstruturaRoute: EstruturaRoute,
  FaqRoute: FaqRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PsicologiaRoute: PsicologiaRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
