import { useEffect, useMemo, useState } from 'react'
import { Copy, ExternalLink, FileText, Link2, Loader2, MessageCircle, RefreshCw, ShieldAlert, XCircle } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { fetchAnamneseStatus, generateAnamneseLink, getAnamneseStatus, invalidateAnamneseLink, type AnamneseRecord } from '@/lib/admin/anamnese'
import type { PatientRecord } from '@/lib/admin/records'

function formatDate(value: string | null | undefined) { return value ? new Date(value).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' }) : '—' }
function firstName(name: string) { return name.trim().split(/\s+/)[0] || 'paciente' }
function DetailSection({ title, items, alert }: { title: string; items: Array<[string, unknown]>; alert?: boolean }) { const visible = items.filter(([, value]) => value !== null && value !== undefined && value !== '' && !(Array.isArray(value) && !value.length)); if (!visible.length) return null; return <Collapsible className={`rounded-lg border ${alert ? 'border-amber-200 bg-amber-50' : 'border-slate-200 bg-white'}`}><CollapsibleTrigger className="flex w-full items-center justify-between p-4 text-left text-sm font-semibold text-slate-800">{title}<span className="text-slate-400">Abrir</span></CollapsibleTrigger><CollapsibleContent className="border-t border-inherit p-4"><dl className="grid gap-4 sm:grid-cols-2">{visible.map(([label, value]) => <div key={label} className="min-w-0"><dt className="text-xs font-medium text-slate-400">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-700">{Array.isArray(value) ? value.join(', ') : String(value)}</dd></div>)}</dl></CollapsibleContent></Collapsible> }

export function AnamneseTab({ patient }: { patient: Pick<PatientRecord, 'id' | 'nome' | 'telefone'> & { token_anamnese?: string | null; token_expira_em?: string | null } }) {
  const [record, setRecord] = useState<AnamneseRecord | null>(null)
  const [token, setToken] = useState<string | null>(patient.token_anamnese ?? null)
  const [expiresAt, setExpiresAt] = useState<string | null>(patient.token_expira_em ?? null)
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const link = token && typeof window !== 'undefined' ? `${window.location.origin}/anamnese/${token}` : ''
  const status = getAnamneseStatus({ token_anamnese: token, token_expira_em: expiresAt }, record)
  const answers = record?.respostas ?? {}
  const currentRisk = answers['pensamentos_morte'] === 'Sim, neste momento' || answers['pensamentos_presentes_agora'] === 'Sim'

  useEffect(() => { let active = true; fetchAnamneseStatus(patient.id).then(data => { if (!active) return; setRecord(data.anamnese); setToken(data.patient.token_anamnese); setExpiresAt(data.patient.token_expira_em) }).catch(() => active && setMessage('Não foi possível carregar a anamnese.')).finally(() => active && setLoading(false)); return () => { active = false } }, [patient.id])
  async function generate() { setBusy(true); setMessage(''); try { const result = await generateAnamneseLink(patient.id); setToken(result.token); setExpiresAt(result.expiresAt); setMessage('Novo link gerado com validade de sete dias.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível gerar o link.') } finally { setBusy(false) } }
  async function copy() { try { await navigator.clipboard.writeText(link); setMessage('Link copiado.') } catch { setMessage('Não foi possível copiar o link automaticamente.') } }
  async function invalidate() { if (!window.confirm('Invalidar o link atual? Ele deixará de funcionar imediatamente.')) return; setBusy(true); setMessage(''); try { await invalidateAnamneseLink(patient.id); setToken(null); setExpiresAt(null); setMessage('Link invalidado.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível invalidar o link.') } finally { setBusy(false) } }
  function whatsapp() { if (!link) return; const phone = (patient.telefone ?? '').replace(/\D/g, ''); const number = phone.length >= 10 ? `55${phone.replace(/^55/, '')}` : ''; const text = `Olá, ${firstName(patient.nome)}. Para continuarmos seu atendimento, peço que preencha sua ficha de anamnese pelo link abaixo. As informações são confidenciais e serão utilizadas exclusivamente para seu atendimento. ${link}`; window.open(`https://wa.me/${number}?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer') }
  const sections = useMemo(() => [
    ['Motivo do atendimento', [['Motivo', answers['motivo_atendimento']], ['Modalidade', answers['modalidade']], ['Início da queixa', answers['inicio_queixa']], ['Impacto na vida', answers['impacto_vida']], ['Expectativa', answers['expectativa_tratamento']], ['Prejuízo (0–10)', answers['escala_prejuizo']]]],
    ['Histórico de saúde', [['Doenças', answers['doencas_detalhes']], ['Cirurgias e internações', answers['cirurgias_detalhes']], ['Alergias', answers['alergias_detalhes']], ['Medicamentos', answers['medicamentos_detalhes']], ['Acompanhamentos', answers['acompanhamento_detalhes']], ['Exames', answers['exames']]]],
    ['Hábitos e rotina', [['Alimentação', answers['alimentacao']], ['Sono', answers['sono']], ['Atividade física', answers['atividade_fisica_detalhes']], ['Substâncias', answers['substancias_detalhes']]]],
    ['Saúde emocional', [['Sintomas', answers['sintomas']], ['Ansiedade (0–10)', answers['escala_ansiedade']], ['Tristeza (0–10)', answers['escala_tristeza']], ['Tratamento anterior', answers['tratamento_anterior_detalhes']], ['Pensamentos de morte', answers['pensamentos_morte']], ['Planejamento', answers['planejamento']], ['Acesso a meios', answers['acesso_meios']], ['Rede de apoio', answers['rede_apoio_nome']], ['Traumas', answers['traumas_detalhes']]]],
    ['Relacionamentos e bem-estar', [['Relacionamentos', answers['relacionamentos']], ['Sexualidade', answers['sexualidade_detalhes']], ['Vida profissional ou acadêmica', answers['vida_profissional']], ['Espiritualidade', answers['espiritualidade_detalhes']]]],
    ['Informações biomédicas', [['Objetivo', answers['objetivo_biomedicina']], ['Peso', answers['peso']], ['Altura', answers['altura']], ['Tratamentos anteriores', answers['tratamentos_anteriores']], ['Anticoagulante', answers['anticoagulante']], ['Gestação/amamentação', answers['gestacao_amamentacao']], ['Doença autoimune', answers['doenca_autoimune']], ['Observações finais', answers['observacoes_finais']]]],
  ] as Array<[string, Array<[string, unknown]>]>, [answers])

  if (loading) return <div className="mt-4 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="size-4 animate-spin" />Carregando anamnese...</div>
  return <div className="mt-4 space-y-5"><Card className="border-slate-200"><CardContent className="p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Status da anamnese</p><p className="mt-1 font-display text-xl font-semibold text-slate-800">{status}</p><dl className="mt-4 grid gap-2 text-sm text-slate-600"><div>Data de geração: {formatDate(record?.link_gerado_em)}</div><div>Validade: {formatDate(expiresAt)}</div><div>Preenchimento: {formatDate(record?.preenchido_em)}</div></dl></div><div className="flex flex-wrap content-start gap-2"><Button disabled={busy} onClick={() => void generate()} className="bg-[#2f8f82] hover:bg-[#26796e]"><Link2 className="mr-2 size-4" />{token ? 'Gerar novo link' : 'Gerar link da anamnese'}</Button>{link && <><Button variant="outline" disabled={busy} onClick={() => void copy()}><Copy className="mr-2 size-4" />Copiar link</Button><Button variant="outline" disabled={busy} onClick={whatsapp}><MessageCircle className="mr-2 size-4" />Enviar pelo WhatsApp</Button><Button variant="outline" asChild><a href={link} target="_blank" rel="noreferrer"><ExternalLink className="mr-2 size-4" />Abrir link</a></Button><Button variant="outline" disabled={busy} onClick={() => void invalidate()} className="text-red-600 hover:text-red-700"><XCircle className="mr-2 size-4" />Invalidar link</Button></>}</div></div>{message && <p role="status" className="mt-4 text-sm text-slate-600">{message}</p>}</CardContent></Card>
    {record?.preenchido_em && <><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => window.print()}><FileText className="mr-2 size-4" />Visualizar ficha</Button><Button variant="outline" onClick={() => window.print()}><FileText className="mr-2 size-4" />Gerar PDF</Button></div>{currentRisk && <div className="flex gap-3 rounded-lg border border-red-300 bg-red-50 p-4 text-sm font-semibold text-red-800"><ShieldAlert className="size-5 shrink-0" />ATENÇÃO — NECESSITA AVALIAÇÃO PRIORITÁRIA</div>}{sections.map(([title, items]) => <DetailSection key={title} title={title} items={items} alert={title === 'Histórico de saúde' && Boolean(answers['alergias_detalhes'] || answers['anticoagulante'] === 'Sim' || answers['gestacao_amamentacao'] === 'Sim')} />)}<DetailSection title="Consentimentos e assinatura" items={[[ 'Consentimento LGPD', record.lgpd_consentimento ? 'Aceito' : 'Não registrado' ], ['Declaração de veracidade', record.declaracao_veracidade ? 'Aceita' : 'Não registrada'], ['Ciência sobre urgência', record.ciencia_urgencia ? 'Aceita' : 'Não registrada'], ['Assinatura eletrônica', record.assinatura_eletronica], ['Versão do termo', record.termo_versao], ['Consentimento em', record.lgpd_data_consentimento]]} /></>}</div>
}
